variable "vault_host" {}
variable "deployer_tfstate_path" {}

variable "region" {}
variable "region_aws" {}
variable "region_db_2" {}
variable "vpc_cidr_block" {}
variable "ubuntu_ami" {}
variable "ubuntu_instance_type" {}
variable "ec2_cidr_block" {}
variable "ec2_port" {}
variable "postgres_engine" {}
variable "postgres_engine_version" {}
variable "postgres_allocated_storage" {}
variable "postgres_instance_class" {}
variable "postgres_port" {}
variable "postgres_db_name" {}
variable "postgres_username" {}
variable "postgres_password" {}
variable "postgres_multi_az" {}
variable "postgres_skip_final_snapshot" {}
variable "postgres_storage_encrypted" {}
variable "postgres_publicly_accessible" {}
variable "postgres_cidr_block" {}
variable "postgres_cidr_block2" {}
variable "s3_bucketname" {}
variable "s3_block_public_acls" {}
variable "s3_block_public_policy" {}
variable "s3_ignore_public_acls" {}
variable "s3_restrict_public_buckets" {}
